In [2]:
import numpy as np

In [3]:
#array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
f = np.random.randint(10,20,5)
print(f)

[14 16 14 18 14]


In [5]:
g = np.array([[1,2,3], [4,5,6]])
print(g)

[[1 2 3]
 [4 5 6]]


In [6]:
zer = np.zeros(3)
ones = np.ones(3)

one_zero = np.array([zer, ones])
print(one_zero)

[[0. 0. 0.]
 [1. 1. 1.]]
