In [2]:
import numpy as np

In [3]:
#array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
f = np.random.randint(10,20,5)
print(f)

[14 16 14 18 14]


In [5]:
g = np.array([[1,2,3], [4,5,6]])
print(g)

[[1 2 3]
 [4 5 6]]


In [6]:
zer = np.zeros(3)
ones = np.ones(3)

one_zero = np.array([zer, ones])
print(one_zero)

[[0. 0. 0.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Create a normally distributed array with mean=3, std=4, size=100
s = np.random.normal(3, 4, 100)

# Plot the distribution
plt.hist(s, bins=20, edgecolor='black', alpha=0.7)
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.title("Histogram of Normally Distributed Data (mean=3, std=4)")
plt.grid(True)

# Show the plot
plt.show()

ModuleNotFoundError: No module named 'matplotlib'